org.gradle.jvmargs=-Xmx6G
org.gradle.parallel=true
# Mod properties
mod.id=mtr
mod.name=Minecraft Transit Railway
mod.description=A Minecraft mod that allows you to build your own transport network with automated trains, boats, cable cars, and planes!
mod.license=MIT
mod.author=Jonathan Ho
mod.group=org.mtr
mod.version=4.1.0-beta.2
mod.homepage=https://www.curseforge.com/minecraft/mc-mods/minecraft-transit-railway
mod.sources=https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway
mod.issues=https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/issues
# Dependencies
dependency.fabric_loader=0.18.4
dependency.elementa=743
dependency.universal_craft=497
# Keys
key.patreon=
key.crowdin=
# Debugging
debug=false
