package org.mtr.mod.api.instancing;

public enum InstancingFallbackReason {
	NONE,
	DISABLED,
	INVALID_SOURCE,
	UNSUPPORTED_RENDER_STAGE,
	UNSUPPORTED_SHADER,
	TRANSLUCENT_NOT_SUPPORTED,
	EMPTY_MODEL,
	MUTABLE_GEOMETRY_NOT_SUPPORTED,
	UPLOAD_FAILED,
	RENDERER_RELOADED,
	CLOSED,
	NOT_IN_RENDER_FRAME,
	FORCED_FALLBACK
}
