package mtr.gui;

public interface IGui {

	int SQUARE_SIZE = 20;
	int TEXT_PADDING = 6;
	int TEXT_FIELD_PADDING = 4;

	int RGB_WHITE = 0xFFFFFF;
	int ARGB_WHITE = 0xFFFFFFFF;
	int ARGB_BLACK = 0xFF000000;
	int ARGB_WHITE_TRANSLUCENT = 0x7FFFFFFF;
	int ARGB_BLACK_TRANSLUCENT = 0x7F000000;
}
