package mtr.gui;

public interface IGui {

	int SQUARE_SIZE = 20;
	int TEXT_PADDING = 6;

	int ARGB_WHITE = 0xFFFFFFFF;
	int ARGB_WHITE_TRANSLUCENT = 0x7FFFFFFF;
	int ARGB_ORANGE_TRANSLUCENT = 0x7FFF7F00;
	int ARGB_BLUE_TRANSLUCENT = 0x7F007FFF;
}
