modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "mtr"
version = "@version@"
displayName = "Minecraft Transit Railway"
authors = "Jonathan Ho"
description = "A Minecraft mod that adds automated train systems into the game."
logoFile = "icon.png"

[[dependencies.mtr]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mtr]]
modId = "minecraft"
mandatory = true
versionRange = "[@minecraft@]"
ordering = "NONE"
side = "BOTH"
